### ISSUE TITLE
Frankfurt eu-central-1 provisioning issue

### ISSUE THREAD

**Issue by farhanumar** [ricardofontanelli/ansible-aws-ec2-provision#2]
I keep getting this

msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: eu-central-1

I am using eu-central-1 / Frankfurt what is causing this limitation, i was able to launch instance with eu-west-1

Ansible version 1.7.2
Boto version is 2.45

With ansible 2.3 and boto 2.45

I got 

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Region eu-west-1a does not seem to be available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"}

Do you know whether i can create instance in Frankfurt eu-central-1 region or not?
What is the cause of error with ansible 2.3 (Compile installed from repo)
What is the cause of error with ansible 1.7.2 not creating instance in frankfurt region but works fine in ireland eu-west-1.

and also 

TASK: [ec2_creation | Add new instance to virtual ec2hosts host group] ********
ok: [localhost] => (item=ec2_instances.instances)

PLAY [ec2hosts] ***************************************************************

GATHERING FACTS ***************************************************************
The authenticity of host '34.248.199.5 (34.248.199.5)' can't be established.
ECDSA key fingerprint is 81:c3:96:06:8b:3d:71:40:7e:02:a1:cf:ad:e4:fb:f8.
Are you sure you want to continue connecting (yes/no)? yes
failed: [34.248.199.5] => {"failed": true, "parsed": false}
invalid output was: /bin/sh: 1: /usr/bin/python: not found

What could be the reason it says "invalid output was: /bin/sh: 1: /usr/bin/python: not found"
once the instance is up and running.

Your video and this repo was huge help thanks

**Comment by ricardofontanelli** [comment]
Hello,

Let's try help you:

1) About Frankfurt (https://github.com/ansible/ansible/pull/9419/commits), some guys have added a new region to the ec2.py file. But I dont know if it's working very well (encryption problems on https://github.com/boto/boto/issues/2741);

2) Here, "Region eu-west-1a does not seem to be available for aws ...", I think there is a typo in eu-west-1a, should be eu-west-1.

There are a lot of changes between ansible and boto versions, and unfortunately i'm not using amazon any more then I can't test it for you on my machine!

When I've recorded the video, I was using ansible 2.0.0 and boto 2.39, both are older than the ones that you are using!

**Comment by farhanumar** [comment]
Just wanted to let you know that boto3 and ansible 2.3 did the job.

Thanks
